### ISSUE TITLE
Conflicting Resolution Reporting on 3.1 in Electron Shepherds’s AVE-HDMI on Wii CPU-40

### ISSUE THREAD

**Issue by Ghost-Mop** [ikorb/gcvideo#110]
Hi, I finished installing two of the new Wii HDMI kits this weekend and my CPU-40 is claiming different resolutions in the three/four most common places but my CPU-20 is reading 720x480p across the board, leading me to question the 40’s behavior.
On the CPU-40’s install, in the OSD I can see 686x912i60 IN, 720x480p60 OUT, but the top right resolution notifier will also state 686x912i60, or whatever slight variation of those numbers but always mismatched to the OSD’s claimed output.
Attached are some pics of the install (yes that is a pink XCM case and probably too much kapton tape)

![AB6EAAA1-7C35-44A7-986C-5C0EAF62236F](https://user-images.githubusercontent.com/17790105/227971408-0652a708-b127-4dbe-8417-0f7475981ef2.jpeg)
![58DEE2B7-02EE-4F7E-809B-BB0E54F256E1](https://user-images.githubusercontent.com/17790105/227971451-1bf029a0-77c6-479d-9b43-97aa8f47ce1b.jpeg)

![12722508-F767-4270-BC22-C096BFAC3E2B](https://user-images.githubusercontent.com/17790105/227971465-05ce0351-547c-430a-a342-5dd20cf69f9e.jpeg)

![42694A94-A83F-4D85-B84B-97657AC90B0B](https://user-images.githubusercontent.com/17790105/227971475-6ce4e1f9-f2b1-4d73-b693-0b0d89aa3e53.jpeg)

I played with a few games, Mario Kart Wii, Mario Parties 8/9, and Animal Crossing: City Folk but I can test out a GameCube game when I get home later, if that could prove useful.

The hardware seems to be working fine and Shane Kent (name-drop!) of Electron Shepherd recommended *against* re-installing unless a solution couldn’t be found here.

Is there a fix for this in the OSD, Priiloader, system menu, etc? Will I be best suited to try and re-flow my install? Is this just a quirk of a CPU-40 install?

I do apologize if this is the wrong place to ask for help!

Quizzically Yours,
Max

**Comment by ikorb** [comment]
You probably have a problem with VDATA0. You could try the [diagnostic mode](https://github.com/ikorb/gcvideo/tree/main/Firmware#diagnostics-mode) to confirm - please be aware that the results are only fully valid if the console is running a 3.0d or later updater at the time (you don't need to actually start the update) because that draws a test pattern at the top of the screen so the diagnostic mode has something known to compare against.

**Comment by ikorb** [comment]
Don't use the stub, use one from a [release](https://github.com/ikorb/gcvideo/releases/tag/GCVideo-DVI_release_3.1)

**Comment by Ghost-Mop** [comment]
![EADDA011-FEFD-4415-968B-1FD462FF78B8](https://user-images.githubusercontent.com/17790105/228059931-7db1ce14-8194-47ee-bf9f-f3d08c0b219a.jpeg)

so it thinks we’re getting crosstalk!

**Comment by ikorb** [comment]
Yes, a problem with VData bit 0 exactly matches the "detects progressive input as interlaced with twice the expected vertical resolution" symptom. Since it is not detected as stuck, it might be floating, shorted to something adjacent or connected to an unrelated signal.

I recommend contacting your hardware vendor about debugging a bad installation since they should know that hardware better.

**Comment by Ghost-Mop** [comment]
I’ll shoot him an email, would you like me to update the thread here or close?

**Comment by ikorb** [comment]
I'll just close it
