### ISSUE TITLE
Corrupt image on some monitors.

### ISSUE THREAD

**Issue by michelmohr** [ikorb/gcvideo#117]
![355583785_1695151070939747_288625719211714025_n](https://github.com/ikorb/gcvideo/assets/9070829/c4665af0-dec5-423e-a9d2-01a78660fb2b)

Is there a known issue or potential fix for this kind of issue with some monitors? Another monitor displays fine. The monitor is not the issue, nor is the cable, tested. Using retro-bit Prism HD adapter.

**Comment by ikorb** [comment]
Did you change any settings? Try resetting them to default by using L+R+X+Y+Start to enter the menu.

Also, try asking the manufacturer about this instead of me - they have a custom firmware archive on their web page which seems to imply to me that they changed something. I have no idea what they changed, so I don't know what your device is actually doing.

**Comment by michelmohr** [comment]
Ok thank you for taking the time to respond, I'll close the issue then. I'll contact the company for support! :)
