### ISSUE TITLE
GCDUAL with M25PE40 instead of M25P40

### ISSUE THREAD

**Issue by jonesaaronj** [ikorb/gcvideo#21]
Would it be possible to add builds to the gcdual with the M25PE40?  I can't seem to flash my GC dual with any existing firmware labeled for the M25P40

**Comment by ikorb** [comment]
Based on a quick glance over the datasheet, it should work for GCVideo itself. I'm not sure if the xsvf file is able to program it or not because I don't know which commands Impact used in there, but as an alternative you could take the .bit file, remove the first 98 bytes and write the remainder directly to the SPI flash with a method of your choice, for example one of the common CH341A-based flash programmers.

**Comment by jonesaaronj** [comment]
Yes, this worked for me perfectly.  Thanks for the help.
