### ISSUE TITLE
YCbCr HDMI Output

### ISSUE THREAD

**Issue by ndoo** [ikorb/gcvideo#22]
Is it possible to passthrough the GameCube raw YCbCr to HDMI?

**Comment by ikorb** [comment]
The code that is currently in the repository always converts the output to RGB.

It would be technically feasible to do so if you bypass the color space conversion and change the infoframes to indicate YCbCr 4:4:4 instead of RGB. If you want YCbCr 4:2:2, additional changes may be required, for example the OSD assumes that it can change the color of a pixel indepently of any other.
