### ISSUE TITLE
Limited HDMI Compatibility

### ISSUE THREAD

**Issue by murderdog** [ikorb/gcvideo#37]
After discovering an issue with sound for myself, I began to test my HDMI mod (Pluto board) on a bunch of my TVs and friends TVs and discovered that this thing has a ton of compatibility issues. Whether it’s an issue with display or sound this really seems to work 50% of the time which is very disappointing. I can’t find anything discussing this through google or other forums so I felt like it’s just me. I assume the external HDMI adapters would give the same result since almost all of them run off Gc video. I'm pretty sure with newer TVs it would be a HDCP issue, not sure about others

Honestly I'm extremely disappointed with the results, as I was looking forward to bring this over friends houses and use it on their TV, but now I think it's just 50/50 whether it'll do anything at all
...
- My desktop monitor displays and plays sound just fine
- My old 2009 TV only displays a picture, no sound
- Another older ~2012 TV, No signal at all
- Sony Bravia, 4k TV. no signal at all,  not sure about RCA because I don't have a converter

Have any of you ever bought an adapter or completed the mod and found it just doesn’t work with your tv? I’m curious

**Is there any sort of fix that could make the signal more compatible such as a converter or anything?**

Let me know, thank you!

Pluto-IIx XC3S200 (GCVideo 3.0d)

**Comment by ikorb** [comment]
Did you try the "Sample rate hack" option in the advanced menu?

**Comment by murderdog** [comment]
> Did you try the "Sample rate hack" option in the advanced menu?

I did attempt it on the 2009 tv with no sound but nothing happened.

I’ll save the settings with it enabled and make the rounds again, but also I’m just curious are there any possible converters or boxes that could be used at all to maybe adapt the HDMI signal to a wider array of displays? I’m not too savvy in TV or theatre equipment so I’m a bit lost. I’m even thinking an HDMI splitter could maybe change something up or maybe not...

Do you think I just have a coincidental set of TVs that are incomparable or there could be something up with my wiring? My soldering seemed pretty solid to me..

**Comment by ikorb** [comment]
The main problem signal is the 54MHz clock line, it's very sensitive to crosstalk from the other signals, resulting in an instable system clock, which can result in all kinds of issues from flickering pixels to no image at all. Since it directly influences the clock signal for the output, the tolerance of the receiving side also comes into play.

Some people had success with using a shielded coaxial wire for the 54MHz clock signal, others had to  carefully rewire everything, making sure that the clock signal was spaced apart from the other signals (e.g. [here](https://github.com/ikorb/gcvideo/issues/34#issuecomment-592644586)).

I'm currently considering dis-recommending the Pluto board because of these issues, the plug-in solutions don't suffer from this as much as their traces tend to be a lot shorter.

**Comment by murderdog** [comment]
I actually have went through and redid all my soldering once again making sure its okay. But obviously I still don't know if there are any issues with it but display still seems fine. When I plugged it in to my 2009 TV it change some sort of resolution setting on the TV that I had to change back. Not sure if that's due to a better solder connection or not.

So I guess I need to find more TVs to test but do you think possibly an EDID emulator would do anything? I'm very tempted to buy one. I could report back here with results if it changed anything..

https://www.pimfg.com/product-detail/HDMI-EDID-1
https://www.hdfury.com/product/dr-hdmi/

What do you think?

**Comment by ikorb** [comment]
An EDID emulator won't help, that only changes the data presented to the source to determine which formats are supported - but GCVideo doesn't even try to check that because I ran out of space.

What might help (but is not guaranteed) is something that processes the video signals, the cheapest thing I can think of is an active (externally-powered) HDMI splitter.

**Comment by murderdog** [comment]
> An EDID emulator won't help, that only changes the data presented to the source to determine which formats are supported - but GCVideo doesn't even try to check that because I ran out of space.
> 
> What might help (but is not guaranteed) is something that processes the video signals, the cheapest thing I can think of is an active (externally-powered) HDMI splitter.

Interesting, what makes the splitter a possibility? I will be investing in a splitter soon to test, do you think an upscaler could also possibly do anything?

My greatest fear is possibly HDCP blocking the signal, but there’s no workaround that available that I know of.

**Comment by ikorb** [comment]
A (fully compliant) HDMI splitter must be able to decrypt an incoming copyprotected signal and re-encrypt it individually for each output, so it needs to fully process the incoming audio/video data and can't just pass it along like an EDID emulator can. Even the "broken" cheap chinese splitters that forget to re-encrypt the output signal have to do that, otherwise they wouldn't be able to decrypt. I wouldn't be surprised though if there are some really cheap splitters that just connect both outputs in parallel, which is why I mentioned "externally-powered" - but I think there is no way they could correctly handle HDCP-encrypted signals because both displays would end up with different encryption keys.

An Upscaler is another example of a device that needs to fully process the incoming A/V data, I didn't mention it as it's a significantly bigger investment than a splitter and I don't know which one I would recommend anyway - the people on the shmups forums might have some recommendations.

HDCP is not an issue here though - displays with an HDMI input are required to support it, but there is no requirement that everything has to be encrypted, GCVideo does not encrypt its output signal, so HDCP does not come into play.

**Comment by murderdog** [comment]
> A (fully compliant) HDMI splitter must be able to decrypt an incoming copyprotected signal and re-encrypt it individually for each output, so it needs to fully process the incoming audio/video data and can't just pass it along like an EDID emulator can. Even the "broken" cheap chinese splitters that forget to re-encrypt the output signal have to do that, otherwise they wouldn't be able to decrypt. I wouldn't be surprised though if there are some really cheap splitters that just connect both outputs in parallel, which is why I mentioned "externally-powered" - but I think there is no way they could correctly handle HDCP-encrypted signals because both displays would end up with different encryption keys.
> 
> An Upscaler is another example of a device that needs to fully process the incoming A/V data, I didn't mention it as it's a significantly bigger investment than a splitter and I don't know which one I would recommend anyway - the people on the shmups forums might have some recommendations.
> 
> HDCP is not an issue here though - displays with an HDMI input are required to support it, but there is no requirement that everything has to be encrypted, GCVideo does not encrypt its output signal, so HDCP does not come into play.

Thank you so much for all this help. I’m going to make a forum post and pass this info along there to see what they say. Will report back to you on results with either device in the future..

**Comment by murderdog** [comment]
Success!!! 

It seems a simple upscaler fixed this issue. From my understanding it’s just the 480p or 480i signal from the pluto board just isn’t detected on many modern displays. I assume as time advances it will get increasingly harder for the newest displays to detect this signal but for now all you need is an upscaler box. For a cheap price I just purchased this one in particular off eBay and it works perfectly, sound and all: https://sewelldirect.com/products/echo-hdmi-upscaler-downscaler

Thank you for your assistance. Hopefully anyone else with this issue can also find this thread.

**Comment by ikorb** [comment]
As far as I know HDMI requires every display to accept at least 480p, so I doubt it's just because of the resolution.

**Comment by murderdog** [comment]
> As far as I know HDMI requires every display to accept at least 480p, so I doubt it's just because of the resolution.

Interesting... who knows then, I wished I had more experience with display issues. I tried to ask on shmups forum like you said but it appears I was ignored or no one really cared about my issue or knew what to suggest.

**Comment by Weario** [comment]
just chiming in to comment on my experience with gcvideo.

I have gcvideo using the Carby adapter for my GameCube, and recently had an installer install Electron AVE on my Wii. Both devices are connected to an Onkyo TX-NR7100 AVR which then outputs to an LG CX Oled tv.

this works flawlessly for the GameCube and Carby, but with the Wii and Electron AVE it keeps losing signal (goes on and off).
I can confirm that the Wii issue is indeed resolved by putting an active hdmi splitter in between the inputs.
However, the Wii also works perfectly when connected directly to the LG tv (without the splitter).

I wonder if this all has anything to do with not enough power coming out of the mini-hdmi port on the Wii or something. I also read somewhere that this could be because some AVRs have issues with DVI signals, but I would have expected the Carby to not work on my AVR either if that were the case.

Hope this info is useful to anyone!
