### ISSUE TITLE
WiiDual update failure 3.0d -> 3.0e

### ISSUE THREAD

**Issue by trapexit** [ikorb/gcvideo#41]
After initiating the update it reports "No compatible firmware found."

**Comment by ikorb** [comment]
I need a bit of additional information, please do the following:

- start the flasher (About->Update firmware), but not the console-side updater
- push left on your IR remote or Z on the gamepad (enters the flash memory dump tool)
- push OK on your IR remote or X on the gamepad (jumps to address 30000)

Your screen should show a lot of hex data with a column of readable characters on the right. The first four characters are the hardware ID, for example my development Gamecube shows "P2XG". What does it show on your system?

**Comment by trapexit** [comment]
DK07

**Comment by ikorb** [comment]
That hardware ID is not among them supported by my software, so you have a vendor-modified firmware on your board. Please contact your vendor for advice, I cannot help you.

**Comment by trapexit** [comment]
There were more than just Dan citrus3000psi Wii Duals? What vendors are supported?

**Comment by ikorb** [comment]
The firmware in this repository only supports WiiDual boards that have the hardware ID "WIID". Since you have a board with a different ID, the firmware was modified by someone else and as far as I know these changes are not publically documented.

It is possible that it is just a different ID, but it is also possible that other firmware modifications are required to use this board. Without public documentation for the exact version of your board I cannot support it. The person who sold it to you is your best point of contact for this, assuming he knows what he sold and  where he got it from if he was only an intermediate.

**Comment by trapexit** [comment]
It's a stock board from Dan which I updated last week using your 3.0d wiidual firmware. I suppose It's possible I corrupted the update but it works seemingly fine otherwise.

**Comment by ikorb** [comment]
In that case Dan seems to have used a modified hardware ID for some reason, possibly because of hardware incompatibilities. Ask him, not me - I'm not doing unpaid support for closed-source hardware with unknown modifications.

**Comment by trapexit** [comment]
OK. Chill. I didn't know there was anything else but his WiiDuals. I'll talk to him about it.

**Comment by drandreas** [comment]
@trapexit I've also ended up with a board that reports DK07 (Took me a while to install it). Did you receive any insights from Dan why the ID is different?

**Comment by drandreas** [comment]
found it: http://dansprojects.com/firmware/WiiDual/
