### ISSUE TITLE
GCVideo 3.0e - missing Bit file for manual upgrade procedure for KNJN Pluto 2x board

### ISSUE THREAD

**Issue by xpertxp** [ikorb/gcvideo#48]
The documentation for KNJN states to use the supplied "*.bit" file to perform a manual flash of the chip using a programmer if you have an older revision.  

The 3.0e that was released, there is no included bit file, however 3.0d does have the included *.bit file in archive gcvideo-3.0d-p2xh-gc-fpgaconf.zip 

Thanks

**Comment by ikorb** [comment]
Why don't you just use the old one and upgrade from that?

**Comment by DoctorDan1986** [comment]
@ikorb How?  How are we supposed to upgrade from the old one without the necessary .bit file?  Is there some reason why we can't be provided with the .bit anymore?

**Comment by ikorb** [comment]
Why do you insist on updating using the bit file? I spent a lot of time creating a system to update the firmware directly from the console, just use that.

**Comment by DoctorDan1986** [comment]
@ikorb I must be missing something.  How, exactly, are we supposed to update Gamecube versions?

**Comment by ikorb** [comment]
If you have a 3.x version installed already: Read the [Updating](https://github.com/ikorb/gcvideo/blob/main/Firmware/README.md#updating) section of the manual.

If you don't have a 3.x version installed already: Install any 3.x version using whatever means you have available and use the previously-referenced console-based update system to update it to the newest release.

**Comment by DoctorDan1986** [comment]
@ikorb So, basically, if we DON'T have a way to run home-brew on the console, we're just SOL.

**Comment by ikorb** [comment]
Yes.

**Comment by DoctorDan1986** [comment]
@ikorb Welp, I'm not gonna say 'You can't do that' because you have every right to dictate the direction your product takes, and I respect that right.  But I have to say that I'm a little disappointed by product philosophies that leaves legacy users eating dust.  I mean, I've GOT a GCloader, so I'm set.  But not everybody has one, or can get one, or can get their hands on a way to load home-brew.

As for me, sometimes I actually LIKE doing things the 'old' way.  Sometimes it's more fun for me to drag out the USB-Blaster or the RS232 instead of just dropping a firmware file on a flash card.

**Comment by ikorb** [comment]
I don't see it as a product. It's just an open-source project that I made because I wanted to have it and I uploaded it so others could use it - I get no commission from the sale of any device that runs that firmware.

Also, the special fake .bit-file was only useful for a single closed-source programming tool from a single vendor that happened to produce something unintended, but useful by feeding it with invalid data. If you actually have a USB blaster or other JTAG programmer available, you can just use the XSVF file to program your device. Since I that one actually gets built automatically (unlike the fake .bit files, which I had to create manually every single time) I do not expect to drop XSVF from the releases any time soon.

And finally, if you dismantle a Gamecube to install a Pluto board inside of it, do yourself a favor and also install a XenoGC clone at the same time. This allows you to run Swiss from a burned disc, which is a really, really useful tool and can manipulate the video settings of most games. For PAL users it's basically a must-have because the PAL cube never officially had progressive video out, so you can't get the best video quality from PAL games without homebrew.
