### ISSUE TITLE
Resident Evil 0 signal reinitialising 

### ISSUE THREAD

**Issue by Bakuku** [ikorb/gcvideo#62]
Hello,

the titel might be wrong (for lack of better wording)

While playing over HDMI:
Whenever you open the inventory (item pickups included), move to a new area (door sequence) or after a cutscene the game will blank for a second or two before outputting any image again.

You can clearly see the GCvideo resolution box (upper right corner) whenever the above mentioned scenario’s transpire.

When outputting over Component, these issues are not present.

The issue is non-existing on Resident Evil Remake (Tested to be sure its Zero only related).

My setup:

- PAL Gamecube
- GCdual
- Wiikey Fusion with SWISS autoboot
- Resident Evil Zero NTSC-U ISO (disc 1) forced to 480p with SWISS
- Samsung TV 

Is this an issue with the software or hardware used?

Thank you

**Comment by ikorb** [comment]
I haven't checked, but it is possible that the game disables video output for a moment, which GCVideo sees as a video mode change, which in turn is translated in a second(-ish) of disabled digital video because that un-confuses some TVs when switching between 240p and 480i.

If that theory is correct, I have a fix for this in the next release, but I do not know when that will happen. I've heard that Swiss has a workaround for this problem too, "Force Video Active" or something like that.

**Comment by Bakuku** [comment]
> I haven't checked, but it is possible that the game disables video output for a moment, which GCVideo sees as a video mode change, which in turn is translated in a second(-ish) of disabled digital video because that un-confuses some TVs when switching between 240p and 480i.
> 
> If that theory is correct, I have a fix for this in the next release, but I do not know when that will happen. I've heard that Swiss has a workaround for this problem too, "Force Video Active" or something like that.

Thanks for the quick reply! I’ll check the SWISS solution and get back to you.

**Comment by ikorb** [comment]
Fix is now released as part of GCVideo 3.1

**Comment by RoflMyPancakes** [comment]
3.1 fixed the problem for many cases but not all for me.

I still have this problem during boot when changing cutscenes. 

It also consistently happens every time I close the map.

Force Video Active didn't change anything.
