### ISSUE TITLE
1080i and 540p support?

### ISSUE THREAD

**Issue by GK6475** [ikorb/gcvideo#66]
Swiss has the 1080i and 540p modes, but both don't work at all with Gcvideo dvi. I tried 960i but it was automatically downscaled to 480p by Gcvideo. Is there any way to stop this downscaling?

**Comment by ikorb** [comment]
True 1080i or 540p are impossible on the Gamecube due to pixel clock limitations. Swiss uses non-standard video timings that somewhat approximate these modes over an analog connection, but since GCVideo is locked to the Gamecube's pixel clock, they will be forwarded to the display as the non-standard video timing they are. Due to performance limitations of the FPGA used by GCVideo, it is not possible to upscale Swiss' modes to actual 1080i/540p as the required TMDS bit clock exceeds what the FPGA can generate.

If you use GCVideo version 2.x, you'll run into the additional problem that assumes that the console only generates video timings that were used by official games, but not any hacked modes used by homebrew software. With GCVideo 3.x, these hacked video modes are not officially supported, but the software tries to switch to a pass-through mode if it detects them. This detection is based on heuristics that are not always reliable, you can try to force the passthrough mode by setting both "Fix resolution" and "Fix sync timing" in the advanced menu to Off.
