### ISSUE TITLE
Life sign indicator

### ISSUE THREAD

**Issue by jmacato** [ikorb/gcvideo#79]
Hi! Is it possible to add a some kind of a heartbeat signal to an LED or perhaps a static message/bitmap image on the HDMI output if there's no valid signal in the GC Video input?

I was wondering about this because i want to know if i fried my gcvideo board or not due to some stupid mistakes.

**Comment by ikorb** [comment]
That's actually a bit complicated. If there is no clock signal from the console, the FPGA cannot do anything at all because there is no other suitable clock source internally or on the existing boards that could be used to generate an output signal or even blink a LED.

If there is a clock signal, GCVideo should blink a LED if the board has one and the blink pattern becomes more complex if video data is recognized. With a working clock signal it is in theory possible to detect that there is no valid video data from the console and generate something internally, but this has not been implemented at this time.

**Comment by jmacato** [comment]
yeah i think the last idea you said there is a good one, hopefully it'll be implemented in some way in the future :)
